Description: Octank PoC Demo with ASG

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "VPC Name"
        Parameters:
          - VPCName
      -
        Label:
          default: "InstanceDetails"
        Parameters:
          - InstanceFlavor
          - MemcacheInstanceFlavor
      -
        Label:
            default: "Instance Quantities"
        Parameters:
            - InstanceQuantity
            - MemcacheNodeQty

Parameters:
  VPCName:
    Type: String
    Default: vpc-oct-demo-lowercase
    Description: 'VPC name.'
  InstanceFlavor:
    Type: String
    Default: t3.medium
    Description: Instance Type
  MemcacheInstanceFlavor:
    Type: String
    Default: cache.r6g.xlarge
    Description: Instance Type
  InstanceQuantity:
    Type: Number
    Default: 10
    Description: 'Quantity of App Instances'
  MemcacheNodeQty:
    Type: Number
    Default: 2
    Description: 'Quantity of App Instances'

Mappings:
  RegionAndResource:
    us-east-1:
      image: ami-0742b4e673072066f
    us-east-2:
      image: ami-05d72852800cbf29e
    us-west-1:
      image: ami-0577b787189839998
    us-west-2:
      image: ami-0518bb0e75d3619ca
## Resources ##
Resources:
  ## VPC public and private subnets (subnets, route tables, IGW, NAT) ##
  PubPrivateVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.31.0.0/16
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', VPC]]
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PubPrivateVPC
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      CidrBlock: 172.31.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', pubsub1]]
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      VpcId: !Ref PubPrivateVPC
      CidrBlock: 172.31.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', pubsub2]]
  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PubPrivateVPC
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      CidrBlock: 172.31.3.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', pvtsub1]]
  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PubPrivateVPC
      AvailabilityZone: !Select
        - '1'
        - !GetAZs ''
      CidrBlock: 172.31.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', pvtsub2]]
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Join [_, [!Ref 'AWS::StackName', IGW]]
  GatewayToInternet:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref PubPrivateVPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref PubPrivateVPC
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable
  NatGateway:
    Type: "AWS::EC2::NatGateway"
    DependsOn: NatPublicIP
    Properties:
      AllocationId: !GetAtt NatPublicIP.AllocationId
      SubnetId: !Ref PublicSubnet1
  NatPublicIP:
    Type: "AWS::EC2::EIP"
    DependsOn: PubPrivateVPC
    Properties:
      Domain: vpc
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref PubPrivateVPC
  PrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
  PrivateSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable
  

  ## App layer (EC2 instance, ALB, Security groups, EC2 SSM Role) ##
  SecurityGroupHTTPALB:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: HTTP-sg-ALB
      GroupDescription: HTTP(S)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref PubPrivateVPC
      Tags:
        - Key: Name
          Value: HTTPSgALB
  SecurityGroupAuroraRDS:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: rds-sg-pvtsubnet-allow
      GroupDescription: MYSQL/Aurora
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 172.31.3.0/24
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 172.31.2.0/24
      VpcId: !Ref PubPrivateVPC
      Tags:
        - Key: Name
          Value: rds-sg-pvtsubnet-allow
  WebSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: secgroup-sg-instc-http-traffic
      GroupDescription: HTTP(S)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref SecurityGroupHTTPALB
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          SourceSecurityGroupId: !Ref SecurityGroupHTTPALB
      VpcId: !Ref PubPrivateVPC
      Tags:
        - Key: Name
          Value: WebSg
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      RoleName: EC2-SSM-SSH
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2Role

  AppInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn:
      - EC2InstanceProfile
      - MemCluster
    Properties:
      ImageId: !FindInMap
        - RegionAndResource
        - !Ref 'AWS::Region'
        - image
      InstanceType: !Ref InstanceFlavor
      IamInstanceProfile: !Ref EC2InstanceProfile
      LaunchConfigurationName: AppInstancesLaunchConfiguration
      SecurityGroups:
        - !Ref WebSecurityGroup
      UserData:
        Fn::Base64:
            !Sub |
                #!/bin/bash
                sudo su
                echo * soft nofile 65536 >> /etc/security/limits.conf
                echo * hard nofile 65536 >> /etc/security/limits.conf
                echo root soft nofile 65536 >> /etc/security/limits.conf
                echo root hard nofile 65536 >> /etc/security/limits.conf
                ulimit -n 65536
                # Install dependecies
                yum update -y
                yum install php php-memcache git mod_ssl php-mysql mysql -y
                # Clone repository
                git clone https://github.com/corriganjeff/aws-ec2-autoscaling-php-app-demo.git
                mv aws-ec2-autoscaling-php-app-demo/src/app/* /var/www/html/
                mv aws-ec2-autoscaling-php-app-demo/src/image/ /var/www/html/
                mv aws-ec2-autoscaling-php-app-demo/src/css/ /var/www/html/
                # Update config files
                sed -i 's/session.save_handler "files"/session.save_handler "memcache"/g' /etc/httpd/conf.d/php.conf
                sed -i 's%session.save_path    "/var/lib/php/session"%session.save_path "${MemCluster.ConfigurationEndpoint.Address}:11211"%g' /etc/httpd/conf.d/php.conf
                # Start apache
                service httpd start
                wget https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-5.4/latest-64bit
                tar -zxf latest-64bit AmazonElastiCacheClusterClient-1.0.1/
                mv AmazonElastiCacheClusterClient-1.0.1/amazon-elasticache-cluster-client.so /usr/lib64/php/modules/
                grep -qF 'extension=amazon-elasticache-cluster-client.so' /etc/php.d/memcached.ini || echo 'extension=amazon-elasticache-cluster-client.so' | sudo tee --append /etc/php.d/memcached.ini
                rm -f latest-64bit*
                cd /usr/lib64
                sudo ln libsasl2.so.3 libsasl2.so.2
                chkconfig httpd on
                echo extension=pdo.so >> /etc/php.ini
                service httpd restart

  AppTierAutoScaling:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: 
      - AppInstances
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinSuccessfulInstancesPercent: 68
        PauseTime: PT30M
        SuspendProcesses: [HealthCheck, ReplaceUnhealthy, AZRebalance, AlarmNotification,
          ScheduledActions]
        WaitOnResourceSignals: 'true'
    Properties:
      AutoScalingGroupName: AppTierAutoScalingGroup
      DesiredCapacity: !Ref InstanceQuantity
      MaxSize: !Ref InstanceQuantity
      MinSize: !Ref InstanceQuantity
      LaunchConfigurationName: !Ref AppInstances
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      TargetGroupARNs:
        - !Ref TargetGroupALB
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: app-instance-asg
        - Key: project
          PropagateAtLaunch: true
          Value: oct-poc
        - Key: deploy-src
          PropagateAtLaunch: true
          Value: oct-cfn-asg
        - Key: team
          PropagateAtLaunch: true
          Value: infra
        - Key: Patch Group
          PropagateAtLaunch: true
          Value: ssm-managed-instances

  TargetGroupALB:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    DependsOn:
      - PubPrivateVPC
    Properties:
      Name: app-targetgroup
      VpcId: !Ref PubPrivateVPC
      TargetType: instance
      Port: 80
      Protocol: HTTP
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 2
      HealthCheckIntervalSeconds: 5
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 10
      Tags:
        - Key: project
          Value: oct-poc
        - Key: deploy-src
          Value: oct-cfn-app
        - Key: team
          Value: infra

  ALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    DependsOn:
      - TargetGroupALB
    Properties:
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Name: alb-app
      SecurityGroups:
        - !Ref SecurityGroupHTTPALB
  ALBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupALB
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ## Data layer (Elasticache memcached node, RDS MySQL) ##
  MemSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Memcached
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '11211'
          ToPort: '11211'
          SourceSecurityGroupId: !Ref WebSecurityGroup
      VpcId: !Ref PubPrivateVPC
  MemSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: Subnet Group for Memcached
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
  MemCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref MemcacheInstanceFlavor
      VpcSecurityGroupIds:
        - !Ref MemSecurityGroup
      CacheSubnetGroupName: !Ref MemSubnetGroup
      ClusterName: web-memcached
      Engine: memcached
      NumCacheNodes: !Ref MemcacheNodeQty
      Port: 11211

  ## CDN layer (S3 bucket) ##
  S3Static:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [-, [!Ref 'AWS::StackName', !Ref 'AWS::AccountId']]
  
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: subnet-group-octankdatabase
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags: 
        - Key: Name
          Value: subnet-group-octankdatabase

  ## Aurora MySQL ##
  AuroraRDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn: SecurityGroupAuroraRDS
    Properties: 
      BackupRetentionPeriod: 14
      DatabaseName: octankdatabase
      DBClusterIdentifier: octankdatabase-cluster
      DBClusterParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: false
      # EnableCloudwatchLogsExports: 
      #   - audit
      #   - error
      #   - general
      #   - slowquery
      EnableHttpEndpoint: true
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: 5.7.mysql_aurora.2.09.2
      KmsKeyId: arn:aws:kms:us-east-1:290475834234:key/14bd1ab8-e84d-4f48-833f-9c9a250f732b
      MasterUsername: admin
      MasterUserPassword: OctankDemo
      Port: 3306
      ScalingConfiguration: 
        AutoPause: true
        MaxCapacity: 8
        MinCapacity: 4
        SecondsUntilAutoPause: 300
      StorageEncrypted: true
      Tags: 
        - Key: testdatabase
          Value: true
      VpcSecurityGroupIds: 
        - !Ref SecurityGroupAuroraRDS

  ##Exec DDL ##
  DDLExecutor:
    Type: AWSUtility::CloudFormation::CommandRunner
    DependsOn: AuroraRDSCluster
    Properties:
      SubnetId: !Ref PrivateSubnet1
      Command: 
        Fn::Sub: 'sudo yum install mysql -y && echo "create table test(id INT NOT NULL AUTO_INCREMENT,tracking_id VARCHAR(100) NOT NULL, request_date DATETIME NOT NULL,PRIMARY KEY ( id ));" > ddl.sql && mysql -u admin --password=OctankDemo -D octankdatabase -h "${AuroraRDSCluster.Endpoint.Address}" < ddl.sql > /command-output.txt'

## Outputs ##
Outputs:
  PubPrivateVPCID:
    Description: VPC ID
    Value: !Ref "PubPrivateVPC"
    Export:
      Name: AppVPCID
  ALBDNS:
    Description: URL to access the application
    Value: !GetAtt ALB.DNSName
    Export:
      Name: ALBAppURL
  StaticBucket:
    Description: Static assets
    Value: !Ref S3Static
    Export:
      Name: S3StaticBucket
  DDLRun:
    Description: Output from DDL executor
    Value: Fn::GetAtt: DDLExecutor.Output